CREATE TABLE IF NOT EXISTS `#__agdetagsearchs_details` (
  `id` int NOT NULL AUTO_INCREMENT,
  `catid` int NOT NULL DEFAULT 0,
  `title`  varchar(255) NOT NULL,
  `alias` varchar(400) CHARACTER SET utf8mb4 COLLATE utf8mb4_bin NOT NULL,
  `fieldtype` varchar(250) NOT NULL DEFAULT '',
  `sort` varchar(250) NOT NULL DEFAULT '',
  `collapse` tinyint unsigned NOT NULL DEFAULT 0,
  `description` mediumtext,
  `state` varchar(100),
  `published` tinyint NOT NULL DEFAULT 0,
  `checked_out` int unsigned NOT NULL DEFAULT 0,
  `checked_out_time` datetime,
  `ordering` int NOT NULL DEFAULT 0,
  `access` int unsigned NOT NULL DEFAULT 0,
  `params` text NOT NULL,
  `language` varchar(7) NOT NULL,
  `publish_up` datetime,
  `publish_down` datetime,
  PRIMARY KEY (`id`),
  KEY `idx_access` (`access`),
  KEY `idx_checkout` (`checked_out`),
  KEY `idx_state` (`published`),
  KEY `idx_catid` (`catid`),
  KEY `idx_language` (`language`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 DEFAULT COLLATE=utf8mb4_unicode_ci;
